import json
import csv
import io
from typing import Dict, Any

from ..domain.schemas import InspectionCase

class ReportExporter:
    """
    Phase 9: Reports and Audit Trail
    Generates official JSON, CSV, and HTML (for PDF printing) case reports.
    """
    
    @classmethod
    def to_json(cls, case: InspectionCase) -> str:
        """Export case as JSON for system integration."""
        return case.json(indent=4)
        
    @classmethod
    def to_csv(cls, case: InspectionCase) -> str:
        """Export case findings to CSV for batch analysis."""
        output = io.StringIO()
        writer = csv.writer(output)
        
        # Header
        writer.writerow([
            "Inspection ID", "Date", "Rule ID", "Rule Title", 
            "Status", "Extracted Value", "Required Value", "Statutory Reference"
        ])
        
        # Rows
        for finding in case.findings:
            writer.writerow([
                case.inspection_id,
                case.updated_at.isoformat(),
                finding.rule_id,
                finding.rule_title,
                finding.status.value,
                finding.extracted_value,
                finding.required_value_or_condition,
                finding.statutory_reference
            ])
            
        return output.getvalue()
        
    @classmethod
    def to_html(cls, case: InspectionCase) -> str:
        """
        Generates an HTML report suitable for saving as an official PDF.
        Includes the mandatory disclaimer for decision-support systems.
        """
        findings_html = ""
        for f in case.findings:
            color = "red" if f.status.value == "SEVERE_VIOLATION" else "orange" if f.status.value == "REQUIRES_MANUAL_REVIEW" else "green"
            findings_html += f"""
            <div style="border-left: 4px solid {color}; padding-left: 15px; margin-bottom: 20px;">
                <h4 style="margin: 0; color: #333;">{f.rule_title}</h4>
                <p style="margin: 5px 0; font-size: 14px; color: #666;"><strong>Status:</strong> {f.status.value}</p>
                <p style="margin: 5px 0; font-size: 14px;"><strong>Detected:</strong> {f.extracted_value}</p>
                <p style="margin: 5px 0; font-size: 14px;"><strong>Required:</strong> {f.required_value_or_condition}</p>
                <p style="margin: 5px 0; font-size: 12px; color: #888;"><em>Ref: {f.statutory_reference}</em></p>
            </div>
            """

        html = f"""
        <html>
        <head>
            <title>Inspection Report: {case.inspection_id}</title>
            <style>
                body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 40px; }}
                .header {{ border-bottom: 2px solid #2e7d32; padding-bottom: 20px; margin-bottom: 30px; }}
                .disclaimer {{ background-color: #fff3e0; border: 1px solid #ffcc80; padding: 15px; border-radius: 5px; font-size: 12px; margin-bottom: 30px; }}
                .meta-table {{ width: 100%; border-collapse: collapse; margin-bottom: 40px; }}
                .meta-table th, .meta-table td {{ padding: 10px; border-bottom: 1px solid #eee; text-align: left; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1 style="color: #2e7d32; margin: 0;">MetriGuard Official Case Report</h1>
                <p style="margin: 5px 0; color: #666;">Generated on: {case.updated_at.strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
            </div>
            
            <div class="disclaimer">
                <strong>IMPORTANT NOTICE:</strong> This is a preliminary automated compliance analysis report generated by MetriGuard decision-support software. All findings require human verification and authorized officer sign-off before regulatory action can be taken.
            </div>
            
            <h3>Case Metadata</h3>
            <table class="meta-table">
                <tr><th>Inspection ID</th><td>{case.inspection_id}</td></tr>
                <tr><th>Officer / User</th><td>{case.user_id} ({case.role})</td></tr>
                <tr><th>Ruleset Version</th><td>{case.ruleset_version}</td></tr>
                <tr><th>Overall Status</th><td style="font-weight: bold;">{case.preliminary_status.value if case.preliminary_status else 'PENDING'}</td></tr>
            </table>
            
            <h3>Detailed Findings ({len(case.findings)})</h3>
            {findings_html}
            
            <div style="margin-top: 50px; border-top: 1px solid #ccc; padding-top: 20px; text-align: center; font-size: 12px; color: #999;">
                MetriGuard SIH26034 Automated System
            </div>
        </body>
        </html>
        """
        return html
